import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "./_components/main/Header";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.className} antialiased`}>
        <div>
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
